name: C/C++ Static Analysis

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang

      - name: Build and analyze
        run: |
          mkdir -p results

          scan-build \
            -sarif \
            -o results \
            g++ main.cpp -o main

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results
          category: clang-static-analyzer
