name: C/C++ Static Analysis

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang clang-tools

      - name: Check Clang tools
        run: |
          clang++ --version
          scan-build --version

      - name: Build and analyze
        run: |
          mkdir -p results

          scan-build \
            -sarif \
            -o results \
            clang++ main.cpp -o main

      - name: Show analyzer results
        run: |
          find results -type f -print

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results
          category: clang-static-analyzer
